[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}